# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e32865a10a88a55e625db3636d7ff2b6f33fdd27ce04e6b82f2ffa04aa8c50bc3b289ecd5760418cc15fcdbbd8398c1f64f35b7538f632d524ba5ebd6ec47e85

test:
  secret_key_base: 07a69200b907f59dd88f1e1943deb1edc4f0fcb9657d314b8c0240bc9e92a7e504f89bfaee2a3f5a43e45a65aa5218706b8c3169933fdb7230cd02cf3ac96013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
